effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_1_joint1
    - panda_1_joint2
    - panda_1_joint3
    - panda_1_joint4
    - panda_1_joint5
    - panda_1_joint6
    - panda_1_joint7
  gains:
    panda_1_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_1_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_1_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_1_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_1_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_1_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_1_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1